### PR TITLE
!!! TASK: Upgrade for Neos 3.0

### PR DESCRIPTION
**Pull request by ComiR**

### CODE REVIEW

**Comment by visay** [comment]
I get the following error in frontend:

```
Tried to configure unknown object "Networkteam\Neos\MailObfuscator\String\Converter\EmailLinkNameConverterInterface" in package "Networkteam.Neos.MailObfuscator".

Please check your Objects.yaml.

Type: Neos\Flow\ObjectManagement\Exception\InvalidObjectConfigurationException
Code: 1184926175
File: Packages/Framework/Neos.Flow/Classes/ObjectManagement/Configuration/ConfigurationBuilder.php
Line: 123

Open Data/Logs/Exceptions/20170201231306e4853f.txt for a full stack trace.

Exception Code	1355480641
Exception Type	Neos\Flow\Core\Booting\Exception\SubProcessException
Log Reference	2017020123130673667e
Thrown in File	Packages/Framework/Neos.Flow/Classes/Core/Booting/Scripts.php
Line	634
```

Also failed unit test:

```
bin/phpunit -c Build/BuildEssentials/PhpUnit/UnitTests.xml Packages/Plugins/Networkteam.Neos.MailObfuscator/Tests/Unit/Fusion/ConvertEmailLinksImplementationTest.php 
PHPUnit 5.4.8 by Sebastian Bergmann and contributors.

EEEEE                                                               5 / 5 (100%)

Time: 29 ms, Memory: 4.00MB

There were 5 errors:

1) Networkteam\Neos\MailObfuscator\Tests\Unit\Fusion\ConvertEmailLinksImplementationTest::emailsAreConverted with data set "just some text not to touch" (' this Is some string with lin...pace  ', ' this Is some string with lin...pace  ')
ReflectionException: Class Networkteam\Neos\MailObfuscator\Fusion\ConvertEmailLinksImplementation does not exist

/var/www/Packages/Framework/Neos.Flow/Tests/BaseTestCase.php:131
/var/www/Packages/Framework/Neos.Flow/Tests/BaseTestCase.php:79
/var/www/Packages/Plugins/Networkteam.Neos.MailObfuscator/Tests/Unit/Fusion/ConvertEmailLinksImplementationTest.php:50

2) Networkteam\Neos\MailObfuscator\Tests\Unit\Fusion\ConvertEmailLinksImplementationTest::emailsAreConverted with data set "single mail link in text" ('Email <a href="mailto:test@ex...om</a>', 'Email <a href="javascript:lin...om</a>')
ReflectionException: Class Networkteam\Neos\MailObfuscator\Fusion\ConvertEmailLinksImplementation does not exist

/var/www/Packages/Framework/Neos.Flow/Tests/BaseTestCase.php:131
/var/www/Packages/Framework/Neos.Flow/Tests/BaseTestCase.php:79
/var/www/Packages/Plugins/Networkteam.Neos.MailObfuscator/Tests/Unit/Fusion/ConvertEmailLinksImplementationTest.php:50

3) Networkteam\Neos\MailObfuscator\Tests\Unit\Fusion\ConvertEmailLinksImplementationTest::emailsAreConverted with data set "multiple mail links in text" ('Email <a href="mailto:test@ex...om</a>', 'Email <a href="javascript:lin...om</a>')
ReflectionException: Class Networkteam\Neos\MailObfuscator\Fusion\ConvertEmailLinksImplementation does not exist

/var/www/Packages/Framework/Neos.Flow/Tests/BaseTestCase.php:131
/var/www/Packages/Framework/Neos.Flow/Tests/BaseTestCase.php:79
/var/www/Packages/Plugins/Networkteam.Neos.MailObfuscator/Tests/Unit/Fusion/ConvertEmailLinksImplementationTest.php:50

4) Networkteam\Neos\MailObfuscator\Tests\Unit\Fusion\ConvertEmailLinksImplementationTest::emailsAreConverted with data set "email address outside of link" ('Email test@example.com should...placed', 'Email test@example.com should...placed')
ReflectionException: Class Networkteam\Neos\MailObfuscator\Fusion\ConvertEmailLinksImplementation does not exist

/var/www/Packages/Framework/Neos.Flow/Tests/BaseTestCase.php:131
/var/www/Packages/Framework/Neos.Flow/Tests/BaseTestCase.php:79
/var/www/Packages/Plugins/Networkteam.Neos.MailObfuscator/Tests/Unit/Fusion/ConvertEmailLinksImplementationTest.php:50

5) Networkteam\Neos\MailObfuscator\Tests\Unit\Fusion\ConvertEmailLinksImplementationTest::emailsAreConverted with data set "email address with space at the beginning" ('Email <a href="mailto: test@e...om</a>', 'Email <a href="javascript:lin...om</a>')
ReflectionException: Class Networkteam\Neos\MailObfuscator\Fusion\ConvertEmailLinksImplementation does not exist

/var/www/Packages/Framework/Neos.Flow/Tests/BaseTestCase.php:131
/var/www/Packages/Framework/Neos.Flow/Tests/BaseTestCase.php:79
/var/www/Packages/Plugins/Networkteam.Neos.MailObfuscator/Tests/Unit/Fusion/ConvertEmailLinksImplementationTest.php:50

ERRORS!
Tests: 5, Assertions: 0, Errors: 5.
```

I have these working in #7 but it's a duplicate PR so I just closed it.

**Comment by ComiR** [comment]
@visay did you just checkout this branch using git or did you install it using composer?
I think it's probably only an autoloading issue because it "works for me" ;)

**Comment by visay** [comment]
@ComiR I did the git checkout. I'll try again with composer.

**Comment by hlubek** [comment]
I also get the failed unit tests. Output in the frontend looks god for me in the demo site. I'll investigate the test failures.

**Comment by visay** [comment]
@ComiR @hlubek the test is now working again with the last commit. frontend also still works. ready for the new release soon?

**Comment by hlubek** [comment]
Done by now ;)

**Pull request merged**
