### PR TITLE
Add compatability with Neos 5.0

### PR DESCRIPTION
**Pull request by ComiR**
Seems to work fine at first glance.

### CODE REVIEW

**Comment by christophlehmann** [comment]
Thanks for the PR, we will test it asap

**Comment by Sebobo** [comment]
Any update on this? :)

**Comment by Sebobo** [comment]
Thx! Can you add a new tag for this change? Then I can update my projects :)

**Comment by hlubek** [comment]
Just drafted a new release with this change:

https://github.com/networkteam/Networkteam.Neos.MailObfuscator/releases/tag/2.4.0

**Pull request merged**
